site_name: littler
site_url: https://github.com/eddelbuettel/littler

## input directory, usually 'docs' which we use for output
docs_dir: src
## output directory, i.e. docs/ on a GH repo
## has to be a subdirectory so need to then copy to ../docs
site_dir: docs

theme:
  name: material
  custom_dir: overrides
  features:
    - tabs
  font:
    text: Lato
  favicon: assets/Rlogo.png
  logo: assets/Rlogo.svg

extra_css:
  - assets/extra.css

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eddelbuettel/littler

nav:
  - Home:
    - index.md
  - Reference:
    - man/littler.md
    - man/r.md
  - Articles:
    - Vignettes: vignettes/overview.md
    - Littler Examples: vignettes/littler-examples.md
    - Littler FAQ: vignettes/littler-faq.md
  - News:
    - news.md
  - Changelog:
    - changelog.md
